spring:
  application:
    name: final-project-backend
  
  # 데이터베이스 설정
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: ${DB_DRIVER}

  # flyway 마이그레이션 설정
  flyway:
    enabled: true
    baseline-on-migrate: false   # 최초 도입 때만 true, 지금은 끄기
    # baseline-version: 0        # 더 이상 필요 없으면 아예 제거
    validate-on-migrate: true    # 마이그레이션 무결성 검사 켜두기
    locations:
      - classpath:db/migration
      - classpath:db/seed

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: -1ms

# JWT 설정
jwt:
  secret: ${JWT_SECRET}  # 환경변수에서 필수로 설정해야 함
  access-expiration: 3600000     # 1시간 (ms)
  refresh-expiration: 604800000  # 7일 (ms)

# 서버 설정
server:
  port: 8080
  servlet:
    context-path: /

# 로깅 설정
logging:
  level:
    com.example: DEBUG
    org.springframework.security: DEBUG

ai:
  fastapi:
    url: ${AI_SERVER_URL} #AI 서버 URL
 
  # OAuth2 설정
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID}
            client-secret: ${KAKAO_CLIENT_SECRET}
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code

            redirect-uri: ${KAKAO_REDIRECT_URI}

            scope:
              - profile_nickname
              - account_email
            client-name: Kakao
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

